baseURL = "https://v.trp.gr/"
languageCode = "en-us"
title = "I'm lazy'"
theme = "hugo-tanka"
author = "Evangelos Tripolitakis"
canonifyurls = true
languagecode = "en"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "I'm lazy"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "javascript", "C"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/vtripolitakis"
    weight = 3
[[menu.primary]]
    name = "Twitter"
    url = "https://twitter.com/vtripolitakis"
    weight = 4